### ISSUE TITLE
Design review for iterv1.0.0 support in Kiali

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/kiali-ui#25]

**Comment by jadeyliu939** [comment]
Design Review 09/03/2020 

- [ ] Add tooltip for the Traffic Control
- [ ] Change Traffic Step size to Max Increment
- [ ] Add onTermination selection dropdown
- [ ] Rearrange the Traffic Control section
- [ ] Allow downloading experiment spec yaml
