### ISSUE TITLE
Show credible intervals and pick up max-min ranges in Kiali using experiment CR

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/kiali-ui#26]

**Comment by jadeyliu939** [comment]
backward compatible for when the max-min range is not populated in the CR
1. With max-min
![Screen Shot 2020-11-19 at 10.20.49 AM.png](https://images.zenhubusercontent.com/577f9bbabf93871ccd9dbd9f/7a012c6b-982a-4f98-af77-a2313f2056a9)

2. Without max-min range
![Screen Shot 2020-11-19 at 10.20.27 AM.png](https://images.zenhubusercontent.com/577f9bbabf93871ccd9dbd9f/0f8521d8-8117-4c4d-8e49-863c37be19f1)

**Comment by jadeyliu939** [comment]
PR created 
Kiali [# 3475](https://github.com/kiali/kiali/pull/3475)

Kiali_ui [# 2015](https://github.com/kiali/kiali-ui/pull/2015)

**Comment by jadeyliu939** [comment]
PR has been merged in to Master
