### ISSUE TITLE
Create Kiali Video

### ISSUE THREAD

**Issue by jadeyliu939** [iter8-tools/kiali-ui#29]
Video 1: canary release (reviews-v2 to reviews-v3), which you do not interrupt to pause/resume. This will succeed and result in all traffic going to reviews-v3.

Video 2: canary release (reviews-v3 to reviews-v4), which you do not interrupt to pause/resume.  This will fail and result in rollback. Remember that reviews-v4 is quite slow.

Video 3: A/B/n rollout (productpage-v1, v2, and v3), which you do not interrupt. Let it finish and converge to the winner.
Also, I would not show in the video the ability to import/export YAML files. It might be confusing to the viewers.

**Comment by jadeyliu939** [comment]
Video 1 - https://ibm.box.com/s/9zt439xldpnmou0ph1fqrzh3d1a22j4b
Video 2 - https://ibm.box.com/s/rh65namzcyw0a395uo5oa2o4ef1fv2cs
Video 3 - https://ibm.box.com/s/w4u33tgeaej1ljdbhuwadov11wq5y4js

**Comment by jadeyliu939** [comment]
@fabolive Please review

**Comment by fabolive** [comment]
I've uploaded the videos to our YouTube channel.
