### ISSUE TITLE
Iter8 Metric for Kiali

### ISSUE THREAD

**Issue by jadeyliu939** [iter8-tools/kiali-ui#5]
Possible Iter8 Metric 
(Currently in Grafana ) 
- [ ] Request Volume / Request Rate
- [ ] Mean Latency 
- [ ] Latency Percentiles

**Comment by jadeyliu939** [comment]
Use Kiali  [Runtime Monitoring](https://kiali.io/documentation/runtimes-monitoring/)

- [ ] Use CRD / monitoringdashboard.monitoring.kiali.io to specify new kiali dashboard
- [ ] Customize the view, for one metric only ( choose-able from dropdown). ( another option is to have a iter8 metric tab, just like outbound/inbound metrics in app/service ).

**Comment by sriumcp** [comment]
Done.
